service: skills-uploader

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  marco:
    handler: handler.marco
    events:
      - http:
          path: /
          method: get
  uploadSkill:
    handler: handler.uploadSkill
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline